name: pdemtools_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - rioxarray 
  - geopandas 
  - opencv 
  - scipy 
  - numba 
  - gdal
  - pandas
  - numpy
  - shapely
  - pyarrow
  - fiona
  - pystac-client
  - sliderule
